server:
  port: 8080


SES:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: rm-cn-kjp4akl9e00053o.rwlb.rds.aliyuncs.com
    port: 3306
    database: smart_device_db
    username: testuser
    password: 123456Test@


  jwt: # 设置jwt签名加密时使用的秘钥
      admin-secret-key: itcast
      # 设置jwt过期时间
      # TODO:恢复正常令牌时长
      admin-ttl: 7200000000 # 7200 000 =2h, 7200 000 000 =2000h
      # 刷新 token 的容忍时间
      refresh-tolerance: 1800000 # 1800 000 = 30min
      # 设置前端传递过来的令牌名称
      admin-token-name: token



spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: ${SES.datasource.driver-class-name}
      url: jdbc:mysql://${SES.datasource.host}:${SES.datasource.port}/${SES.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${SES.datasource.username}
      password: ${SES.datasource.password}
  rabbitmq:
    host: localhost  # 默认 localhost
    port: 5672                 # 默认端口
    username: guest            # 默认用户名
    password: guest            # 默认密码
    virtual-host: /             # 虚拟主机，默认 /
    publisher-confirm-type: correlated  # 开启发布确认（可选）
    publisher-return: true      # 开启消息退回（可选）
    listener:
      simple:
        acknowledge-mode: manual  # 手动确认模式（推荐）
        prefetch: 1               # 每次只处理一个消息（防过载）
        retry:
          enabled: true           # 启用重试机制
          max-attempts: 3         # 最多重试3次
          initial-interval: 2000  # 初始重试间隔

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.SES.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure=DEBUG:
    com:
      SES:
        mapper: debug
        service: info
        controller: info


